### ISSUE TITLE
Drools.org URL warns of insecure link and potential non-privacy

### ISSUE THREAD

**Issue by bit4man** [kiegroup/drools-website#171]
![Screenshot from 2021-09-02 11-06-48](https://user-images.githubusercontent.com/1713562/131868716-9a005984-50ea-4669-bb82-20ebd76fc953.png)

Several links, in particular this CSS link is using http and not https, and causes warnings:
```
<link href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css" rel="stylesheet">
```

Suggest making every link "local" to speed up loading and ensuring security and better CI/CD testing.

**Comment by jsight** [comment]
https://github.com/kiegroup/drools-website/pull/172

**Comment by tarilabs** [comment]
Thank you for spotting a non-https link.

I was curious @bit4man if you could share some details how you obtain that warning; asking because I've tried with Firefox and Chrome which I use with default settings, and I don't any warning in the url bar. Thanks.

**Comment by jsight** [comment]
@tarilabs I didn't see a big warning either, however, I looked at the network tab in the developer tools. In there, I could see that this particular stylesheet wasn't loaded at all due to the use of http on an https page.

I'm not sure what part of my browser (Chrome) rejected it, but it could have been a plugin. This was the only rejected resource that I saw in the panel.

**Comment by tarilabs** [comment]
Yes I can see the error when following procedure described in this https://github.com/kiegroup/drools-website/issues/171#issuecomment-912003204 , thanks

**Comment by bit4man** [comment]
The warning comes when you look at why the "lock" has a dash through it. This is a symbol of the encryption having issues, and when you go to see the details you get the following warning:
![Screenshot from 2021-09-02 16-57-25](https://user-images.githubusercontent.com/1713562/131915188-7de54d2d-4ec4-41e7-b5a5-c4b5ae46b7f0.png)
I am unable to do a screen dump of short summary screen you get when clicking the lock - basically the message is the same: Part of this page is unencrypted.

**Comment by jsight** [comment]
@bit4man - It does seem like some browsers do not show that error as they just block the resource completely. I have two instances of Chrome that just report "The page is secure" with no caveats.

**Comment by bit4man** [comment]
> @bit4man - It does seem like some browsers do not show that error as they just block the resource completely. I have two instances of Chrome that just report "The page is secure" with no caveats.

It would depend on the browser settings and it's privacy enforcement.  The fact that the cert doesn't point to a trusted/named CA is also a problem, but I just wanted to let "someone" know that with moderate->high security settings, this is what you see.

**Comment by tarilabs** [comment]
I've re-checked after the recent migration to JBake and no more resources are failing to load:

![image](https://user-images.githubusercontent.com/1699252/141999831-d425e885-1303-4e75-ae4b-f51e9c615210.png)

(the warning relates to JS mandated by Red Hat)

don't hesitate to report again if you see something not working as expected, thanks!
